# --- CONEXÃO COM O MYSQL (Baseado no seu Workbench) ---
# A porta é 3306 e o IP é 127.0.0.1 conforme a sua imagem
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/hotel_management?createDatabaseIfNotExist=true
spring.datasource.username=root
# COLOQUE A SUA SENHA DO MYSQL ABAIXO:
spring.datasource.password=Proa@2026
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- CONFIGURAÇÕES DO HIBERNATE ---
# O 'update' criará as tabelas 'clients', 'employees', etc., automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect